### ISSUE TITLE
复现精度

### ISSUE THREAD

**Issue by fxwispig** [princewang1994/TextSnake.pytorch#1]
您好，您有测过复现的精度能达到或者接近作者的精度吗

**Comment by princevandev** [comment]
很高兴您关注我的工作，目前指标的计算正在进行中，后续会放出预训练模型和指标计算，而且一些训练的trick还没有加上去，请关注这个repo的后续commit

**Comment by fxwispig** [comment]
期待您的更新

**Comment by princevandev** [comment]
@fxwispig 预训练模型和精度已放出~欢迎debug
