### ISSUE TITLE
How to get the  Square or Rectangle by the test  detect results?

### ISSUE THREAD

**Issue by 10183308** [princewang1994/TextSnake.pytorch#10]
First , Wish you a Happy New Year.

I have some problem ,maybe you can help me . Thakn you very much.

I trained the model with my datasets . Now the detector results is some ploygons  which have three
formats (center point , tangent line,text region).  How can I use the results to get the rectangle or square?

Thank you very much.

**Comment by princevandev** [comment]
@10183308 Hi，TextSnake is designed for cured text detection. So prediction cannot be perfectly converted to rectangle or square. Anyway if you require rectangle prediction, maybe you can try EAST or TextBox(++) etc. 
On the other hand, minimum enclosing rectangle algorithm can be applied if you want TextSnake to output rectangle, but performance should degrade.
