### ISSUE TITLE
in loss.py  what is the difference between tr_mask and train_mask?

### ISSUE THREAD

**Issue by Jackandrome** [princewang1994/TextSnake.pytorch#15]
` train_mask = train_mask.view(-1)  
 tr_mask = tr_mask.contiguous().view(-1)`

After doing that, you use them by [train_mask * tr_mask]. Do you want to exclude the tough text?

**Comment by princevandev** [comment]
Hi, @Jackandrome, generally speaking, some texts in datasets should be ignored because of their unclear appearance(blur, occlusion etc.). These texts are marked in the annotation file(.mat). For such samples, I just do not compute loss of corresponding region.
