### ISSUE TITLE
problematic point removal

### ISSUE THREAD

**Issue by Godricly** [princewang1994/TextSnake.pytorch#17]
The point removal of in TextInstance removes all qualified points independently. Which is not working well in some cases.
```
before [[  15    0]
 [1216    0]
 [1219    0]
 [  13   16]]

after [[15  0]
 [13 16]]
```

![oops_screenshot_05 03 2019](https://user-images.githubusercontent.com/17567935/53798804-f4102b00-3f73-11e9-8d13-b19b3db8e02e.png)
The image is from the latest ArT dataset.

**Comment by princevandev** [comment]
Hi @Godricly,  this is exactly a problem. This removal operation is designed to remove some unnecessary annotation points in some polygons. There should be a judgment condition to ignore those polygons which have fewer points than 4(if it has only 4 points, keep all of them). Welcome a PR after solving this problem.

**Comment by Godricly** [comment]
suppose the polygon contains n(n>=4) points. What you are trying to do is to loop for at most n-4 times, and to remove the point which changes the area least. Is that correct?

**Comment by Godricly** [comment]
@princewang1994 Please check if this is the correct one. I'm not sure about the area changing threshold. 
```python
        loops = points.shape[0] - 4
        for loop_index in range(loops):
            sub_polygons = [np.delete(points, i, axis=0) for i in range(points.shape[0])]
            sub_polygon_areas = np.array([cv2.contourArea(v) for v in sub_polygons])
            diff = np.abs(sub_polygon_areas - ori_area)/ori_area
            min_diff_point = np.argmin(diff)
            if diff.min() > 0.017:
                break
            points = np.delete(points, min_diff_point, axis=0)
        self.points = np.array(points)
```
