### ISSUE TITLE
find_bottom logic understanding issue

### ISSUE THREAD

**Issue by Godricly** [princewang1994/TextSnake.pytorch#18]
HI @princewang1994, I found the logic to find snake head is a little different from the paper. But I have to say it is really difficult to handle. Compared with selecting the 2 edges with M nearest to -1. Here you use a proposal based method selecting all possible edges which has M < -0.7. 
```python
    if len(pts) > 4:
        e = np.concatenate([pts, pts[:3]])
        candidate = []
        for i in range(1, len(pts) + 1):
            v_prev = e[i] - e[i - 1]
            v_next = e[i + 2] - e[i + 1]
            if cos(v_prev, v_next) < -0.7:
                candidate.append((i % len(pts), (i + 1) % len(pts), norm2(e[i] - e[i + 1])))
```
The next refining step is somehow confusing.
if this logic is True:
```python
candidate[0][0] == candidate[1][1] or candidate[0][1] == candidate[1][0]
```
you are visiting the same edge from 2 different direction, which seems impossible for me.

**Comment by Godricly** [comment]
my bad, I got the condition logic.

**Comment by princevandev** [comment]
Well, I'm closing this issue😆
