### ISSUE TITLE
the error in running demo.py

### ISSUE THREAD

**Issue by cryptolalia** [princewang1994/TextSnake.pytorch#20]
```
Loading from ./save/example/textsnake_vgg_10.pth
Start testing TextSnake.
detect 0 / 300 images: img650.jpg.
Traceback (most recent call last):
  File "demo.py", line 133, in <module>
    main()
  File "demo.py", line 119, in main
    inference(model, detector, test_loader)
  File "demo.py", line 77, in inference
    batch_result = detector.detect(tr_pred, tcl_pred, sin_pred, cos_pred, radii_pred)  # (n_tcl, 3)
  File "/home/crypa/TextSnake.pytorch/util/detection.py", line 204, in detect
    detect_result = self.build_tcl(tcl, sin_pred, cos_pred, radii_pred)
  File "/home/crypa/TextSnake.pytorch/util/detection.py", line 164, in build_tcl
    _, conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```
Due to time, I didn't reach 200epoch according to the training requirements.
I tried to test the code with 10epoch. 
so run` CUDA_VISIBLE_DEVICES=0 python demo.py --checkepoch 10 example`
But got the above error.so sorry,I am a newbie,could  u help me?

**Comment by princevandev** [comment]
It might be the problem of opencv-python version, it should be ok if you keep cv2's version consistent of mine(3.4.0).

**Comment by LearnerInGithub** [comment]
@princewang1994  
Why the demo.py give me such error？
Traceback (most recent call last):
  File "demo.py", line 140, in <module>
    main()
  File "demo.py", line 123, in main
    inference(model, detector, test_loader)
  File "demo.py", line 72, in inference
    tr_pred = output[idx, 0:2].softmax(dim=0).data.cpu().numpy()
AttributeError: 'Tensor' object has no attribute 'softmax'

**Comment by princevandev** [comment]
Hi, @LearnerInGithub , which PyTorch version you're using? This code can only run with 0.4.0 or above, double check it.

**Comment by vlad3996** [comment]
@cryptolalia probably, you're using openCV v.4.0.0 or higher. 
So change  
` _, conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`
to
`conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

**Comment by cryptolalia** [comment]
ty very much,i am glad that u could give suggestion




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            ssguaishou
                            
                            
                                
                                    邮箱：ssguaishou@sina.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 04/13/2019 01:31, vlad3996 wrote: @cryptolalia probably, you're using openCV v.4.0.0 or higher.
So change
 _, conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
to
conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/princewang1994/TextSnake.pytorch","title":"princewang1994/TextSnake.pytorch","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/princewang1994/TextSnake.pytorch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vlad3996 in #20: @cryptolalia probably, you're using openCV v.4.0.0 or higher. \r\nSo change  \r\n` _, conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`\r\nto\r\n`conts, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`"}],"action":{"name":"View Issue","url":"https://github.com/princewang1994/TextSnake.pytorch/issues/20#issuecomment-482658354"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/princewang1994/TextSnake.pytorch/issues/20#issuecomment-482658354",
"url": "https://github.com/princewang1994/TextSnake.pytorch/issues/20#issuecomment-482658354",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
