### ISSUE TITLE
About the result of demo.py

### ISSUE THREAD

**Issue by cryptolalia** [princewang1994/TextSnake.pytorch#21]
I managed to finish the demo.py, but I got the .txt result, how should I convert it to the corresponding image result display?I am sorry to trouble you again.

**Comment by princevandev** [comment]
Hi, @cryptolalia, after ruling demo.py you will .txt file in `output/` and image result in `vis/`, if you pull the latest repo, I have changed visualization directory to `vis/$(EXP_NAME)_test`.

**Comment by jun214384468** [comment]
I want to know what the exp_name should be set to.

**Comment by princevandev** [comment]
@jun214384468 `exp_name` is the name of one experiments (e.g. at one time you set lr=2e-4 and bs=64, you can set `exp_name` to `lr2e-4_bs64`) for identifying different hyper-parameter settings.

**Comment by jun214384468** [comment]
> @jun214384468 `exp_name` is the name of one experiments (e.g. at one time you set lr=2e-4 and bs=64, you can set `exp_name` to `lr2e-4_bs64`) for identifying different hyper-parameter settings.

Thank you!

**Comment by jun214384468** [comment]
> lr2e-4_bs64

Hello, if I want to train this parameter in pycharm, how should I assign it?

**Comment by princevandev** [comment]
Just set program argments in like this: 
![批注 2019-11-12 111057](https://user-images.githubusercontent.com/15909795/68638654-35ae9800-053d-11ea-8b0a-a4527d2881bc.png)

**Comment by jun214384468** [comment]
Thank you very much for your guidance.
