### ISSUE TITLE
How to get image_list.txt?

### ISSUE THREAD

**Issue by sherif7810** [princewang1994/TextSnake.pytorch#24]
Hi, I download the dataset from [here](http://www.robots.ox.ac.uk/~vgg/data/scenetext/) then ran `python dataset/synth-text/make_list.py` and I couldn't find image_list.txt.

Is it necessary to download the dataset from [this link](https://github.com/princewang1994/TextSnake.pytorch/blob/master/dataset/synth-text/README.md)?

**Comment by princevandev** [comment]
Sorry, it is my fault, `make_list.py` is only for making `data/synth-text/gt/*.txt` and without `image_list.txt`, for getting `image_list.txt` you can simply run 
```bash
ls gt/ > image_list.txt
```
in synth-text root. Or you can download here: [image_list.txt](https://github.com/princewang1994/TextSnake.pytorch/files/3110673/image_list.txt)

**Comment by sherif7810** [comment]
It works. Thanks. :)

**Comment by sherif7810** [comment]
I get an error at random times:
`loss_pos = F.cross_entropy(predict[pos], target[pos], reduction='sum')
  File "/home/sherif/Envs/TextSnake_venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/sherif/Envs/TextSnake_venv/lib/python3.6/site-packages/torch/nn/functional.py", line 975, in log_softmax
    return input.log_softmax(dim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

**Comment by princevandev** [comment]
I seems that in some situations, the `n_pos` might be 0(due to blank annotation or too heavy augmentation) so it causes this error. This is almost impossible  if your batch size is big enough, maybe your batch size is set too small, try to use bigger batch size. 

Another solution is change function `ohem` as following:
```python
def ohem(self, predict, target, train_mask, negative_ratio=3.):
    pos = (target * train_mask).byte()
    neg = ((1 - target) * train_mask).byte()

    n_pos = pos.float().sum()

    if n_pos.item() > 0:
        loss_pos = F.cross_entropy(predict[pos], target[pos], reduction='sum')
        loss_neg = F.cross_entropy(predict[neg], target[neg], reduction='none')
        n_neg = min(int(neg.float().sum().item()), int(negative_ratio * n_pos.float()))
    else:
        loss_pos = 0.
        loss_neg = F.cross_entropy(predict[neg], target[neg], reduction='none')
        n_neg = 100
    loss_neg, _ = torch.topk(loss_neg, n_neg)

    return (loss_pos + loss_neg.sum()) / (n_pos + n_neg).float()
```

**Comment by sherif7810** [comment]
I can't use a batch size larger than 2.
Thanks. :)

**Comment by sherif7810** [comment]
I still get error:
```Start training TextSnake.
Epoch: 0 : LR = 0.0001
(0 / 429375) - Loss: 3.3805 - tr_loss: 0.7713 - tcl_loss: 0.7961 - sin_loss: 0.5057 - cos_loss: 0.4078 - radii_loss: 0.8996
(50 / 429375) - Loss: 3.4198 - tr_loss: 0.7345 - tcl_loss: 0.7905 - sin_loss: 0.5054 - cos_loss: 0.1623 - radii_loss: 1.2271
(100 / 429375) - Loss: 3.2209 - tr_loss: 0.6912 - tcl_loss: 0.5796 - sin_loss: 0.4406 - cos_loss: 0.0574 - radii_loss: 1.4520
(150 / 429375) - Loss: 3.1461 - tr_loss: 0.6014 - tcl_loss: 0.5752 - sin_loss: 0.4080 - cos_loss: 0.1760 - radii_loss: 1.3855
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 223, in main
    train(model, train_loader, criterion, scheduler, optimizer, epoch, logger)
  File "train.py", line 73, in train
    criterion(output, tr_mask, tcl_mask, sin_map, cos_map, radius_map, train_mask)
  File "/home/sherif/Envs/TextSnake_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sherif/Projects/العمل/New TextSnake/TextSnake.pytorch/network/loss.py", line 63, in forward
    tcl_mask[train_mask * tr_mask].long())
  File "/home/sherif/Envs/TextSnake_venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/sherif/Envs/TextSnake_venv/lib/python3.6/site-packages/torch/nn/functional.py", line 975, in log_softmax
    return input.log_softmax(dim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by sherif7810** [comment]
The cause is sometimes `tcl_pred[train_mask * tr_mask]` is tensor([], grad_fn=<TakeBackward>).

**Comment by princevandev** [comment]
Well, `ohem` has no problem now. it can be resolved by a few code modifying, add a condition to set to 0.0 if there are not any positive samples.
