### ISSUE TITLE
How can I test trained model for my test images?

### ISSUE THREAD

**Issue by johnSmith1990** [princewang1994/TextSnake.pytorch#25]
Thanks for your great work and codes.

I followed your commands:
1. I used pre-train phase.
2. used total-text dataset to improve training model.
3. test on total-text database to evaluate model.

now I want to evaluate model on my sample images. I run demo.py but it need mat file of my sample images, while I dont want to give .mat file. I want to test for images in which i don't have their gt files. 

regards,John

**Comment by princewang1994** [comment]
Thanking for your attention to my work, pure inference needs dataset modification, which will be added to  this repo soon.

**Comment by princewang1994** [comment]
@johnSmith1990 pretrained models on my machine and pure inference script are released(see README.md) hope it can help you. I'll close this issue.
