### ISSUE TITLE
How to transform text instances  to canonical form using the predicted geometries like fig 9 in paper?

### ISSUE THREAD

**Issue by ghost** [princewang1994/TextSnake.pytorch#26]
I tried put minimum enclosing rectangle text instances to recognition model but the results very poor. I saw Figure 9 in the article but didn't know how to do it. Can you suggest some algorithm for do it

**Comment by princevandev** [comment]
Sorry I have not found this method named "local geometries" too. Hope [this question](https://mathematica.stackexchange.com/questions/5676/how-to-peel-the-labels-from-marmalade-jars-using-mathematica) can help you. (I did not try it neither)

**Comment by ghost** [comment]
Thanks for answering, i will try it
