### ISSUE TITLE
中文文字检测模型

### ISSUE THREAD

**Issue by summerwbb** [princewang1994/TextSnake.pytorch#28]
你好，请问中文文字检测的模型能分享一下吗

**Comment by princevandev** [comment]
你好，暂时没训练过中文检测的数据集

**Comment by summerwbb** [comment]
那会对检测中文有影响吗？我想检测中英文还有韩语日语字幕。

**Comment by princevandev** [comment]
目前训练的数据集中只包括英文，检测字幕这样的水平文字用cptn应该会更好，TextSnake主要用于任意形状的文字检测

**Comment by smartcatdog** [comment]
> 目前训练的数据集中只包括英文，检测字幕这样的水平文字用cptn应该会更好，TextSnake主要用于任意形状的文字检测

您好，想请教下，对于椭圆章的弯曲文字检测大佬您这边有什么指导不

**Comment by princevandev** [comment]
Textsnake可以做弯曲文本的，另外也可以试一下一下PSENet，目前比较好的baseline。
