### ISSUE TITLE
IndexError: index 732 is out of bounds for axis 0 with size 512

### ISSUE THREAD

**Issue by FakerYFX** [princewang1994/TextSnake.pytorch#3]
![image](https://user-images.githubusercontent.com/19235054/50758789-29630a00-129e-11e9-9b1f-62d2cc933139.png)
您好，这个是说训练集的坐标有问题吗？
@princewang1994

**Comment by princevandev** [comment]
请问是自己的数据集还是totaltext数据集？从iteration的数量来看应该是自己的数据集，可能是坐标超出了图片的大小造成的，具体可能需要调试看原因

**Comment by FakerYFX** [comment]
嗯嗯，是自己的数据集，所以你的ignore.list里面就是totaltext数据集中有问题的图片吗？如果需要改成适应icdar2017那种中文的数据集，主要需要改哪些部分的代码呢?
@princewang1994

**Comment by princevandev** [comment]
对的，有一些图片出现三角形或者很诡异的标注，就把他们ignore掉了，建议开始训练自己的数据之前先写个for循环把TotalText的所有数据都过一遍，把有问题的ignore掉

**Comment by FakerYFX** [comment]
好的，谢谢

**Comment by Sophia-cai** [comment]
您好，我使用的是totaltext数据集，运行demo.py测试的时候，也报了这个错，请问您知道测试集中的哪些图片有问题吗？或者您可以分享一下如何找出问题图片的for循环代码吗？
`detect 0 images: img646.jpg.
detect 0 images: img622.jpg.
Traceback (most recent call last):
  File "demo.py", line 91, in <module>
    main()
  File "demo.py", line 77, in main
    inference(model, detector, test_loader)
  File "demo.py", line 45, in inference
    batch_result = detector.detect(tr_pred, tcl_pred, sin_pred, cos_pred, radii_pred)  # (n_tcl, 3)
  File "/home/pc001/AI_work/TextSnake.pytorch/util/detection.py", line 187, in detect
    tcl = self.build_tcl(tcl_pred_mask, sin_pred, cos_pred, radii_pred)
  File "/home/pc001/AI_work/TextSnake.pytorch/util/detection.py", line 166, in build_tcl
    tcl_right = self.mask_to_tcl(sin_pred, cos_pred, radii_pred, tcl_pred, (x_init, y_init), direct=-1)
  File "/home/pc001/AI_work/TextSnake.pytorch/util/detection.py", line 99, in mask_to_tcl
    while tcl_mask[int(y_shift), int(x_shift)]:
**IndexError: index 512 is out of bounds for axis 1 with size 512**`
@princewang1994 @xieyufei1993

**Comment by princevandev** [comment]
有一些图片有一些问题，最新的commit修复了部分越界的bug，尝试拉取最新的代码，也许问题就解决了~

**Comment by LearnerInGithub** [comment]
@princewang1994 Could you share the ignore.list for TotalText? Seems it missing in the git repository..

**Comment by princevandev** [comment]
@LearnerInGithub, ignore.list is removed in the latest version of this code because I fixed some bugs in the data loading process. Please just set `ignore_list=None`.
