### ISSUE TITLE
merge contour issue

### ISSUE THREAD

**Issue by johnSmith1990** [princewang1994/TextSnake.pytorch#31]
Hi Dear. I want to use `detector.merge_contours` method to merge overlapped contours. but it gives an error `"ValueError: too many values to unpack (expected 2)"` at  this line: `cont_i, disk_i = all_contours[i]`. thank you for your help. can you give insight that how does merge contour work? what are `cont_i disk_i ` s? thanks

**Comment by princewang1994** [comment]
Hi, first you should output the all_contours[i] to make sure that it has 2
elements, first is contour and the other is disk. Here `disk` is a sequence
of disk with (center, radius), see in the original paper. And `contour` is
the contour points array after drawing the disks in an all-zero mat (than
as the input of cv2.findContour).

The main idea of `merge_contours` is that if one contour "steps into" the
other one, they should be one contiguous text instance e.g. word "hello"
and "world" are often annotated as a single text instance. We use function
stride to judge if one instance "step into" another one: From the first or
the last disk's center, we step in the direction of the textsnake by 0.3
times of the radius. if this point is in another contour, they are
overlapped.

Hope this can help you.

**Comment by johnSmith1990** [comment]
thank for your reply. but i am confused.  this line : `contours, output = detector.detect(image)` gives list of contours and each of them is an array not 2 output. here is output : [https://ibb.co/ZVZPVMF](url)

**Comment by johnSmith1990** [comment]
thanks. I got it.
