### ISSUE TITLE
请问您可以分享将synthtext数据集格式转换为icdar格式的脚本嘛？

### ISSUE THREAD

**Issue by ZDDEAN** [princewang1994/TextSnake.pytorch#35]

**Comment by princevandev** [comment]
我没有把synthtext格式转换成icdar哈，只是我写了一个python脚本把SynthText单个annotation文件转换成每张图片一个的文本文件，然后写了一个dataset直接去读这个文件，具体可以参考https://github.com/princewang1994/TextSnake.pytorch/blob/master/dataset/synth-text/make_list.py
