### ISSUE TITLE
训练完一个epoch后就不再往下运行了是为什么

### ISSUE THREAD

**Issue by zhuliqian** [princewang1994/TextSnake.pytorch#4]
![screenshot from 2019-01-08 19-45-58](https://user-images.githubusercontent.com/17901084/50830833-f135f700-1383-11e9-8c3e-d19a3577e09a.png)

**Comment by zhuliqian** [comment]
第二次train()方法里的for循环不运行了

**Comment by princevandev** [comment]
接下来本来是要进入validation的，把断点打到validation里面看一下具体是哪句代码卡住了

**Comment by zhuliqian** [comment]
谢谢，莫名其妙的好了，笑哭，

**Comment by LearnerInGithub** [comment]
> 接下来本来是要进入validation的，把断点打到validation里面看一下具体是哪句代码卡住了

@princewang1994 我也遇到这个问题， 定位到卡在val阶段for循环中加载测试集， 请问这个可能的原因是什么？

**Comment by princevandev** [comment]
@LearnerInGithub 可能是加载数据的时候get_item里面进死循环了，如果是用自己的数据集的话不知道是不是数据集里面有一些无法处理的情况，建议直接进到validation的dataset数据加载语句里面看一下是不是哪个函数进了死循环，或者尝试pull最新的代码看看
