### ISSUE TITLE
SynthText link of baidu cloud does not work

### ISSUE THREAD

**Issue by nasirkamal** [princewang1994/TextSnake.pytorch#46]
[Link](https://pan.baidu.com/s/17Gk301SwsnoESM1jQZRq0g) mentioned on [page](https://github.com/princewang1994/TextSnake.pytorch/tree/master/dataset/synth-text) to download SynthText from baidu cloud gives 404 error. Either the link is expired or it has been moved. Can someone kindly fix that error.

**Comment by princevandev** [comment]
@nasirkamal  I tried just now but it still work fine, please check your network environment. Don't forget inputing extracting code.
