### ISSUE TITLE
too many "torch.uint8 Warning"

### ISSUE THREAD

**Issue by xmyhhh** [princewang1994/TextSnake.pytorch#47]
C:\w\1\s\windows\pytorch\aten\src\ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:/w/1/s/windows/pytorch/aten/src\ATen/native/IndexingUtils.h:20)

**Comment by klarajanouskova** [comment]
In network/loss.py, whenever you are indexing, cast the index source array to bool:  
```
pos = (target * train_mask).bool()
neg = ((1 - target) * train_mask).bool()
(train_mask * tr_mask).bool()
```

**Comment by princevandev** [comment]
@xmyhhh this will happen in the latest pytorch version where the none-bool indexing operation has been deprecated. @klarajanouskova said is right that if you change all "byte()" to "bool()" in `network/loss.py`([this line](https://github.com/princewang1994/TextSnake.pytorch/blob/master/network/loss.py#L11)) will resolve this problem. 
Don't forget to change the "train_mask", "tr_mask" and "tcl_mask" in [forward function](https://github.com/princewang1994/TextSnake.pytorch/blob/master/network/loss.py#L28) also ^_^

I'll fix this bug in next version, thank you very much @xmyhhh @klarajanouskova .

**Comment by xmyhhh** [comment]
Problem solved perfectly！ thanks~   I will close this issue
