### ISSUE TITLE
what is the format of dataset ?

### ISSUE THREAD

**Issue by 10183308** [princewang1994/TextSnake.pytorch#9]
Could you tell me what is the format of the dataset?

Could the ICDAR 2015 dataset work?

the data format like this 👍 

x1 , y1 , x2, y2 , x3, y3 ,x4 ,y4 hello

thank you very much

**Comment by princevandev** [comment]
Hi @10183308 , in this repo, TotalText-dataset are used, which can referred to [this](https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text), ICDAR 2015 can but not yet included in this code.  For now you can create other dataset/icdar.py like dataset/totaltext.py and modify little code to adapt for ICDAR, my code on ICDAR are coming soon, thx for watching
